export const ADD_NOTICE = 'ADD_NOTICE'
export const ADD_NOTICE_LOADING = 'ADD_NOTICE_LOADING'
export const ADD_NOTICE_SUCCESS = 'ADD_NOTICE_SUCCESS'
export const ADD_NOTICE_FAILED = 'ADD_NOTICE_FAILED'

export const GET_NOTICE = 'GET_NOTICE'
export const GET_NOTICE_LOADING = 'GET_NOTICE_LOADING'
export const GET_NOTICE_SUCCESS = 'GET_NOTICE_SUCCESS'

export const UPDATE_NOTICE = 'UPDATE_NOTICE'
export const UPDATE_NOTICE_LOADING = 'UPDATE_NOTICE_LOADING'
export const UPDATE_NOTICE_SUCCESS = 'UPDATE_NOTICE_SUCCESS'
export const UPDATE_NOTICE_FAILED = 'UPDATE_NOTICE_FAILED'

export const DELETE_NOTICE = 'DELETE_NOTICE'
export const DELETE_NOTICE_LOADING = 'DELETE_NOTICE_LOADING'
export const DELETE_NOTICE_SUCCESS = 'DELETE_NOTICE_SUCCESS'
export const DELETE_NOTICE_FAILED = 'DELETE_NOTICE_FAILED'