
// MANAGE BILLING PLANS & MORE
export const SELECT_PLAN = 'SELECT_PLAN'
export const SELECT_PLAN_LOADING = 'SELECT_PLAN_LOADING'
export const SELECT_PLAN_SUCCESS = 'SELECT_PLAN_SUCCESS'
export const SELECT_PLAN_FAILED = 'SELECT_PLAN_FAILED'

export const PLAN_TYPE_MONTHLY = 'PLAN_TYPE_MONTHLY'
export const PLAN_TYPE_QUARTERLY = 'PLAN_TYPE_QUARTERLY'
export const PLAN_TYPE_YEARLY = 'PLAN_TYPE_YEARLY'

// CHARGE BASED ON EMPLOYEES :: start[::15] -> 150+::


// Choose default Payment Method:: 
//  Paypal/ Stripe ... Our Wallet<Dazzle Wallet>, Mpesa(mpesa no.), Equitel(acc no.), Co-op bank(acc no.), Flutterwave 

export const ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD'
export const ADD_PAYMENT_METHOD_LOADING = 'ADD_PAYMENT_METHOD_LOADING'
export const ADD_PAYMENT_METHOD_SUCCESS = 'ADD_PAYMENT_METHOD_SUCCESS'
export const ADD_PAYMENT_METHOD_FAILED = 'ADD_PAYMENT_METHOD_FAILED'

export const REMOVE_PAYMENT_METHOD = 'REMOVE_PAYMENT_METHOD'
export const REMOVE_PAYMENT_METHOD_LOADING = 'REMOVE_PAYMENT_METHOD_LOADING'
export const REMOVE_PAYMENT_METHOD_SUCCESS = 'REMOVE_PAYMENT_METHOD_SUCCESS'
export const REMOVE_PAYMENT_METHOD_FAILED = 'REMOVE_PAYMENT_METHOD_FAILED'

// Auto Renew Subscription :: Toggle ON/ OFF
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION'
export const ADD_SUBSCRIPTION_LOADING = 'ADD_SUBSCRIPTION_LOADING'
export const ADD_SUBSCRIPTION_SUCCESS = 'ADD_SUBSCRIPTION_SUCCESS'
export const ADD_SUBSCRIPTION_FAILED = 'ADD_SUBSCRIPTION_FAILED'

export const CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION'
export const CANCEL_SUBSCRIPTION_LOADING = 'CANCEL_SUBSCRIPTION_LOADING'
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS'
export const CANCEL_SUBSCRIPTION_FAILED = 'CANCEL_SUBSCRIPTION_FAILED'


// Billing Details include: [Invoice No. due date, Amount, Payment method, Type, Status<Pending|Complete|Failed>] *VAT