export const ADD_PAYROLL = 'ADD_PAYROLL'
export const ADD_PAYROLL_LOADING = 'ADD_PAYROLL_LOADING'
export const ADD_PAYROLL_SUCCESS = 'ADD_PAYROLL_SUCCESS'
export const ADD_PAYROLL_FAILED = 'ADD_PAYROLL_FAILED'

// pending | completed | rejected?
export const APPROVE_PAYROLL = 'APPROVE_PAYROLL'
export const APPROVE_PAYROLL_LOADING = 'APPROVE_PAYROLL_LOADING'
export const APPROVE_PAYROLL_SUCCESS = 'APPROVE_PAYROLL_SUCCESS'
export const APPROVE_PAYROLL_FAILED = 'APPROVE_PAYROLL_FAILED'

export const LOAD_PAYROLL = 'LOAD_PAYROLL'
export const LOAD_PAYROLL_LOADING = 'LOAD_PAYROLL_LOADING'
export const LOAD_PAYROLL_SUCCESS = 'LOAD_PAYROLL_SUCCESS'
export const LOAD_PAYROLL_FAILED = 'LOAD_PAYROLL_FAILED'

export const UPDATE_PAYROLL = 'UPDATE_PAYROLL'
export const UPDATE_PAYROLL_LOADING = 'UPDATE_PAYROLL_LOADING'
export const UPDATE_PAYROLL_SUCCESS = 'UPDATE_PAYROLL_SUCCESS'
export const UPDATE_PAYROLL_FAILED = 'UPDATE_PAYROLL_FAILED'

export const DELETE_PAYROLL = 'UPDATE_PAYROLL'
export const DELETE_PAYROLL_LOADING = 'DELETE_PAYROLL_LOADING'
export const DELETE_PAYROLL_SUCCESS = 'DELETE_PAYROLL_SUCCESS'
export const DELETE_PAYROLL_FAILED = 'DELETE_PAYROLL_FAILED'