export const ADD_PROJECT = 'ADD_PROJECT'
export const ADD_PROJECT_LOADING = 'ADD_PROJECT_LOADING'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAILED = 'ADD_PROJECT_FAILED'

export const GET_PROJECT = 'GET_PROJECT'
export const GET_PROJECT_LOADING = 'GET_PROJECT_LOADING'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_FAILED = 'GET_PROJECT_FAILED'

export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const UPDATE_PROJECT_LOADING = 'UPDATE_PROJECT_LOADING'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED'

export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DELETE_PROJECT_LOADING = 'DELETE_PROJECT_LOADING'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED'

export const VALIDATE_PROJECT_CACHE = 'VALIDATE_PROJECT_CACHE'
export const INVALIDATE_PROJECT_CACHE = 'INVALIDATE_PROJECT_CACHE'