export const ADD_RECIEPT = 'ADD_RECIEPT'
export const ADD_RECIEPT_LOADING = 'ADD_RECIEPT_LOADING'
export const ADD_RECIEPT_SUCCESS = 'ADD_RECIEPT_SUCCESS'
export const ADD_RECIEPT_FAILED = 'ADD_RECIEPT_FAILED'

export const LOAD_RECIEPT = 'LOAD_RECIEPT'
export const LOAD_RECIEPT_LOADING = 'LOAD_RECIEPT_LOADING'
export const LOAD_RECIEPT_SUCCESS = 'LOAD_RECIEPT_SUCCESS'
export const LOAD_RECIEPT_FAILED = 'LOAD_RECIEPT_FAILED'

export const UPDATE_RECIEPT = 'UPDATE_RECIEPT'
export const UPDATE_RECIEPT_LOADING = 'UPDATE_RECIEPT_LOADING'
export const UPDATE_RECIEPT_SUCCESS = 'UPDATE_RECIEPT_SUCCESS'
export const UPDATE_RECIEPT_FAILED = 'UPDATE_RECIEPT_FAILED'

export const DELETE_RECIEPT = 'UPDATE_RECIEPT'
export const DELETE_RECIEPT_LOADING = 'DELETE_RECIEPT_LOADING'
export const DELETE_RECIEPT_SUCCESS = 'DELETE_RECIEPT_SUCCESS'
export const DELETE_RECIEPT_FAILED = 'DELETE_RECIEPT_FAILED'