export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
export const ADD_EMPLOYEE_LOADING = 'ADD_EMPLOYEE_LOADING'
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_FAILED = 'ADD_EMPLOYEE_FAILED'

export const GET_EMPLOYEE = 'GET_EMPLOYEE'
export const GET_EMPLOYEE_LOADING = 'GET_EMPLOYEE_LOADING'
export const GET_EMPLOYEE_FAILED = 'GET_EMPLOYEE_FAILED'

export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE'
export const UPDATE_EMPLOYEE_LOADING = 'UPDATE_EMPLOYEE_LOADING'
export const UPDATE_EMPLOYEE_FAILED = 'UPDATE_EMPLOYEE_FAILED'

export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
export const DELETE_EMPLOYEE_LOADING = 'DELETE_EMPLOYEE_LOADING'
export const DELETE_EMPLOYEE_FAILED = 'DELETE_EMPLOYEE_FAILED'

export const VALIDATE_EMPLOYEE_CACHE = 'VALIDATE_EMPLOYEE_CACHE'
export const INVALIDATE_EMPLOYEE_CACHE = 'INVALIDATE_EMPLOYEE_CACHE'