export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
export const ADD_EMPLOYEE_LOADING = 'ADD_EMPLOYEE_LOADING'
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_FAILED = 'ADD_EMPLOYEE_FAILED'

export const LOAD_EMPLOYEE = 'LOAD_EMPLOYEE'
export const LOAD_EMPLOYEE_LOADING = 'LOAD_EMPLOYEE_LOADING'
export const LOAD_EMPLOYEE_SUCCESS = 'LOAD_EMPLOYEE_SUCCESS'
export const LOAD_EMPLOYEE_FAILED = 'LOAD_EMPLOYEE_FAILED'

export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE'
export const UPDATE_EMPLOYEE_LOADING = 'UPDATE_EMPLOYEE_LOADING'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_FAILED = 'UPDATE_EMPLOYEE_FAILED'

export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
export const DELETE_EMPLOYEE_LOADING = 'DELETE_EMPLOYEE_LOADING'
export const DELETE_EMPLOYEE_FAILED = 'DELETE_EMPLOYEE_FAILED'

// Simply return an employee object with all these details. An action should trigger an update i.e {...state, action:payload}


// ROLES ::
// export const ADD_EMPLOYEE_ROLE = 'ADD_EMPLOYEE_ROLE'
// export const ADD_EMPLOYEE_ROLE_LOADING = 'ADD_EMPLOYEE_ROLE_LOADING'
// export const ADD_EMPLOYEE_ROLE_SUCCESS = 'ADD_EMPLOYEE_ROLE_SUCCESS'
// export const ADD_EMPLOYEE_ROLE_FAILED = 'ADD_EMPLOYEE_ROLE_FAILED'

// export const LOAD_EMPLOYEE_ROLE = 'LOAD_EMPLOYEE_ROLE'
// export const LOAD_EMPLOYEE_ROLE_LOADING = 'LOAD_EMPLOYEE_ROLE_LOADING'
// export const LOAD_EMPLOYEE_ROLE_SUCCESS = 'LOAD_EMPLOYEE_ROLE_SUCCESS'
// export const LOAD_EMPLOYEE_ROLE_FAILED = 'LOAD_EMPLOYEE_ROLE_FAILED'

// export const UPDATE_EMPLOYEE_ROLE = 'UPDATE_EMPLOYEE_ROLE'
// export const UPDATE_EMPLOYEE_ROLE_LOADING = 'UPDATE_EMPLOYEE_ROLE_LOADING'
// export const UPDATE_EMPLOYEE_ROLE_SUCCESS = 'UPDATE_EMPLOYEE_ROLE_SUCCESS'
// export const UPDATE_EMPLOYEE_ROLE_FAILED = 'UPDATE_EMPLOYEE_ROLE_FAILED'

// export const DELETE_EMPLOYEE_ROLE = 'DELETE_EMPLOYEE_ROLE'
// export const DELETE_EMPLOYEE_ROLE_LOADING = 'DELETE_EMPLOYEE_ROLE_LOADING'
// export const DELETE_EMPLOYEE_ROLE_SUCCESS = 'DELETE_EMPLOYEE_ROLE_SUCCESS'
// export const DELETE_EMPLOYEE_ROLE_FAILED = 'DELETE_EMPLOYEE_ROLE_FAILED'

// // AWARDS
// export const ADD_EMPLOYEE_AWARD = 'ADD_EMPLOYEE_AWARD'


// // PROMOS
// export const ADD_EMPLOYEE_PROMOTION = 'ADD_EMPLOYEE_PROMOTION'

// // TRANSFER
// export const APPROVE_EMPLOYEE_TRANSFER = 'APPROVE_EMPLOYEE_TRANSFER'

// // CONTRACTRACT
// export const TERMINATE_EMPLOYEE_CONTRACT = 'TERMINATE_EMPLOYEE_CONTRACT'

// // RESIGNATION ...

// //LEAVE
// export const APPROVE_EMPLOYEE_LEAVE = 'APPROVE_EMPLOYEE_LEAVE'

// // NOTES
// export const ADD_EMPLOYEE_NOTE = 'ADD_EMPLOYEE_NOTE'

// // WARNING
// export const SET_EMPLOYEE_WARNING = 'SET_EMPLOYEE_WARNING'
// export const SET_EMPLOYEE_WARNING_LOADING = 'SET_EMPLOYEE_WARNING_LOADING'
// export const SET_EMPLOYEE_WARNING_SUCCESS = 'SET_EMPLOYEE_WARNING_SUCCESS'
// export const SET_EMPLOYEE_WARNING_FAILED = 'SET_EMPLOYEE_WARNING_FAILED'

// export const LOAD_EMPLOYEE_WARNING = 'LOAD_EMPLOYEE_WARNING'
// export const LOAD_EMPLOYEE_WARNING_LOADING = 'LOAD_EMPLOYEE_WARNING_FAILED'
// export const LOAD_EMPLOYEE_WARNING_SUCCESS = 'LOAD_EMPLOEE_WARNING_SUCCESS'
// export const LOAD_EMPLOYEE_WARNING_FAILED = 'LOAD_EMPLOYEE_WARNING_FAILED'

// export const UPDATE_EMPLOYEE_WARNING = 'UPDATE_EMPLOYEE_WARNING'
// export const UPDATE_EMPLOYEE_WARNING_LOADING = 'UPDATE_EMPLOYEE_WARNING_LOADING'
// export const UPDATE_EMPLOYEE_WARNING_SUCCESS = 'UPDATE_EMPLOYEE_WARNING_SUCCESS'
// export const UPDATE_EMPLOYEE_WARNING_FAILED = 'UPDATE_EMPLOYEE_WARNING_FAILED'

// export const DELETE_EMPLOYEE_WARNING = 'DELETE_EMPLOYEE_WARNING'
// export const DELETE_EMPLOYEE_WARNING_LOADING = 'DELETE_EMPLOYEE_WARNING_LOADING'
// export const DELETE_EMPLOYEE_WARNING_SUCCESS = 'DELETE_EMPLOYEE_WARNING_SUCCESS'
// export const DELETE_EMPLOYEE_WARNING_FAILED = 'DELETE_EMPLOYEE_WARNING_FAILED'

// CACHE
export const VALIDATE_EMPLOYEE_CACHE = 'VALIDATE_EMPLOYEE_CACHE'
export const INVALIDATE_EMPLOYEE_CACHE = 'INVALIDATE_EMPLOYEE_CACHE'