export const ADD_DEPARTMENT = 'ADD_DEPARTMENT'
export const ADD_DEPARTMENT_LOADING = 'ADD_DEPARTMENT_LOADING'
export const ADD_DEPARTMENT_SUCCESS = 'ADD_DEPARTMENT_SUCCESS'
export const ADD_DEPARTMENT_FAILED = 'ADD_DEPARTMENT_FAILED'

export const GET_DEPARTMENT = 'GET_DEPARTMENT'
export const GET_DEPARTMENT_LOADING = 'GET_DEPARTMENT_LOADING'
export const GET_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS'
export const GET_DEPARTMENT_FAILED = 'GET_DEPARTMENT_FAILED'