export const ADD_DEPARTMENT = 'ADD_DEPARTMENT'
export const ADD_DEPARTMENT_LOADING = 'ADD_DEPARTMENT_LOADING'
export const ADD_DEPARTMENT_SUCCESS = 'ADD_DEPARTMENT_SUCCESS'
export const ADD_DEPARTMENT_FAILED = 'ADD_DEPARTMENT_FAILED'

export const LOAD_DEPARTMENT = 'GET_DEPARTMENT'
export const LOAD_DEPARTMENT_LOADING = 'GET_DEPARTMENT_LOADING'
export const LOAD_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS'
export const LOAD_DEPARTMENT_FAILED = 'GET_DEPARTMENT_FAILED'

export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT'
export const UPDATE_DEPARTMENT_LOADING = 'UPDATE_DEPARTMENT_LOADING'
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS'
export const UPDATE_DEPARTMENT_FAILED = 'UPDATE_DEPARTMENT_FAILED'

export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'
export const DELETE_DEPARTMENT_LOADING = 'DELETE_DEPARTMENT'
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS'
export const DELETE_DEPARTMENT_FAILED = 'DELETE_DEPARTMENT_FAILED'