export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT'
export const UPLOAD_DOCUMENT_UPLOADING = 'UPLOAD_DOCUMENT_UPLOADING'
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS'
export const UPLOAD_DOCUMENT_FAILED = 'UPLOAD_DOCUMENT_FAILED'

export const DOWNLOAD_DOCUMENT = 'DOWNLOAD_DOCUMENT'
export const DOWNLOAD_DOCUMENT_DOWNLOADING = 'DOWNLOAD_DOCUMENT_DOWNLOADING'
export const DOWNLOAD_DOCUMENT_SUCCESS = 'DOWNLOAD_DOCUMENT_SUCCESS'
export const DOWNLOAD_DOCUMENT_FAILED = 'DOWNLOAD_DOCUMENT_FAILED'

// TODO: support multiple documents/ file uploads [max:5]

export const CHANGE_VISIBILITY = 'CHANGE_VISIBILITY'
export const CHANGE_VISIBILITY_LOADING = 'CHANGE_VISIBILITY_LOADING'
export const CHANGE_VISIBILITY_SUCCESS = 'CHANGE_VISIBILITY_SUCCESS'
export const CHANGE_VISIBILITY_FAILED = 'CHANGE_VISIBILITY_FAILED'

// PRIVATE<only you> | PROTECTED<anyone with the link within & account> | PUBLIC<literally anonyone>