/**
 * * User settings persists in DB & indexDB respectively
 * ? @pattern: Singeton, enforce only one global settings Object
 */

// export const ADD_SETTING = 'ADD_SETTING'
// export const ADD_SETTING_SUCCESS = 'ADD_SETTING_SUCCESS'
// export const ADD_SETTING_FAILED = 'ADD_SETTING_FAILED'

// //SETTINGS UPDATE MUST SYNC WITH UI & CACHE
// export const UPDATE_SETTING = 'UPDATE_SETTING'
// export const UPDATE_SETTING_FAILED = 'UPDATE_SETTING_FAILED'

// export const DELETE_SETTING = 'DELETE_SETTING'
// export const DELETE_SETTING_SUCCESS = 'DELETE_SETTING_FAILED'

export const ADD_THEME = 'ADD_THEME'
export const ADD_THEME_LOADING = 'ADD_THEME_LOADING'
export const ADD_THEME_SUCCESS = 'ADD_THEME_SUCCESS'
export const ADD_THEME_FAILED = 'ADD_THEME_FAILED'

export const LOAD_THEME = 'LOAD_THEME'
export const LOAD_THEME_LOADING = 'LOAD_THEME_LOADING'
export const LOAD_THEME_SUCCESS = 'LOAD_THEME_LOADING'
export const LOAD_THEME_FAILED = 'LOAD_THEME_FAILED'

export const UPDATE_THEME = 'UPDATE_THEME'
export const UPDATE_THEME_LOADING = 'UPDATE_THEME_LOADING'
export const UPDATE_THEME_SUCCESS = 'UPDATE_THEME_SUCCESS'
export const UPDATE_THEME_FAILED = 'UPDATE_THEME_FAILED'

export const DELETE_THEME = 'DELETE_THEME'
export const DELETE_THEME_LOADING = 'DELETE_THEME_LOADING'
export const DELETE_THEME_SUCCESS = 'DELETE_THEME_SUCCESS'
export const DELETE_THEME_FAILED = 'DELETE_THEME_FAILED'

export const ENABLE_NOTIFICATION = 'ENABLE_NOTIFICATION'
export const ENABLE_NOTIFICATION_LOADING = 'ENABLE_NOTFICATION_LOADING'
export const ENABLE_NOTIFICATION_SUCCESS = 'ENABLE_NOTIFICATION_SUCCESS'
export const ENABLE_NOTIFICATION_FAILED = 'ENABLE_NOTIFICATION_FAILED'

export const DEACTIVATE_ACCOUNT = 'DEACTIVATE_ACCOUNT'
export const DEACTIVATE_ACCOUNT_LOADING = 'DEACTIVATE_ACCOUNT_LOADING'
export const DEACTIVATE_ACCOUNT_SUCCESS = 'DEACTIVATE_ACCOUNT_SUCCESS'
export const DEACTIVATE_ACCOUNT_FAILED = 'DEACTIVATE_ACCOUNT_FAILED'

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const DELETE_ACCOUNT_LOADING = 'DELETE_ACCOUNT_LOADING'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED'

// VERSION, FONT_SIZE, ACCOUNT, STORAGE, E.G AUTO_BACKUP?
// AFFILIATE_LINK