export const ADD_TASK = 'ADD_TASK'
export const ADD_TASK_LOADING = 'ADD_TASK_LOADING'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED'

export const LOAD_TASK = 'LOAD_TASK'
export const LOAD_TASK_LOADING = 'LOAD_TASK_LOADING'
export const LOAD_TASK_SUCCESS = 'LOAD_TASK_SUCCESS'
export const LOAD_TASK_FAILED = 'LOAD_TASK_FAILED'

export const UPDATE_TASK = 'UPDATE_TASK'
export const UPDATE_TASK_LOADING = 'UPDATE_TASK_LOADING'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED'

export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_TASK_LOADING = 'DELETE_TASK_LOADING'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED'